logs = {
    "Log 64": "Day 289: Passed by planetary body A2834 this morning — just as expected in our approach corridor. Navigation systems confirm we’re still on course. Crew’s in good spirits, minimal corrections needed. All cryo-passengers remain stable with no reported anomalies. Everything's running exactly as it should. If we keep this pace, we’ll reach the new colony sector right on schedule. No surprises. Good day.",

    "Log 65": "Day 301: Can’t stop thinking about Cheryl today. She was 12 when I left — still carrying that ridiculous stuffed bird everywhere she went. By the time we return, she’ll be in her 50s. That part of this mission never gets easier to think about. I hope this trip actually means something. I hope she understands why I signed on for this. If nothing else, I just want to make it home... and see her again.",

    "Log 66": "Day 302: Came across unexpected debris during today’s scan — fragments of what looks like ship plating and possibly a torn heat shield. It’s strange. There aren’t supposed to be any other missions routed through this sector, and no distress signals were detected. Even odder, this region is flagged as lifeless — deep-range probes showed no activity for decades. Crew is running analysis, but it’s... off. Something about the scorch patterns doesn’t match up.",

    "Log 67": " Day 302.2: Sent Time and Grandal out in suits to get a closer look at some of the larger debris chunks. Before we lost contact, Grandal was saying the exposed tech didn’t look like anything we’ve seen — even hinted it was more advanced than ours. That was the last clear transmission. Just... static after that. No return signal. No telemetry. Then, a few minutes later — a loud thud on the portside hull. No breach alarms triggered, but I’m logging this in case something’s already aboard.",

    "Log 68": " Day 303: They're gone. I dont—I don’t know how else to write this. People... people are missing. We found blood near the docking corridor but no bodies. It’s like something picked them off one by one. I tried to initiate evac protocol—pods either destroyed or j-jammed. Couldn’t get one to launch. This was our only way out. Or… maybe not. There’s one other ship onboard. A prototype short-range scout with enough fuel to reach the colony planet… or maybe home. It’s hidden. A failsafe only command knows about. Locked behind an admin terminal in the control room. The access code will activate the engine bay terminal. That unlocks a sealed vault door… you’ll need my fob to open it. Just one more thing—important: whatever’s on board... it doesn’t just kill. It pretends. I saw Skylynn-Rae. My wife. Gone for years. She looked exactly the same as the day she died. Then I saw Cheryl. My daughter. Alive. Smiling. But there are only 2. I’m sure of it. 2 of them. Remember that."
}